from abc import ABC, abstractmethod
from typing import List, Optional


class IEventRepository(ABC):
    @abstractmethod
    def add(self, event) -> object: ...
    @abstractmethod
    def get_by_id(self, event_id: str) -> Optional[object]: ...
    @abstractmethod
    def get_all(self) -> List: ...
    @abstractmethod
    def update(self, event) -> object: ...
    @abstractmethod
    def delete(self, event_id: str) -> bool: ...
    @abstractmethod
    def find_by_organizer(self, organizer_id: str) -> List: ...
    @abstractmethod
    def find_by_category(self, category) -> List: ...
    @abstractmethod
    def find_available(self) -> List: ...
    @abstractmethod
    def find_by_title(self, title: str) -> List: ...


class IUserRepository(ABC):
    @abstractmethod
    def add(self, user) -> object: ...
    @abstractmethod
    def get_by_id(self, user_id: str) -> Optional[object]: ...
    @abstractmethod
    def get_all(self) -> List: ...
    @abstractmethod
    def update(self, user) -> object: ...
    @abstractmethod
    def delete(self, user_id: str) -> bool: ...
    @abstractmethod
    def find_by_email(self, email: str) -> Optional[object]: ...
    @abstractmethod
    def find_active(self) -> List: ...
    @abstractmethod
    def find_blocked(self) -> List: ...


class IRegistrationRepository(ABC):
    @abstractmethod
    def add(self, registration) -> object: ...
    @abstractmethod
    def get_by_id(self, reg_id: str) -> Optional[object]: ...
    @abstractmethod
    def get_all(self) -> List: ...
    @abstractmethod
    def update(self, registration) -> object: ...
    @abstractmethod
    def find_by_user(self, user_id: str) -> List: ...
    @abstractmethod
    def find_by_event(self, event_id: str) -> List: ...
    @abstractmethod
    def find_active_by_event(self, event_id: str) -> List: ...
    @abstractmethod
    def find_waitlisted(self, event_id: str) -> List: ...
    @abstractmethod
    def find_by_user_and_event(self, user_id: str, event_id: str) -> Optional[object]: ...


class INotificationRepository(ABC):
    @abstractmethod
    def add(self, notification) -> object: ...
    @abstractmethod
    def get_by_id(self, notif_id: str) -> Optional[object]: ...
    @abstractmethod
    def get_all(self) -> List: ...
    @abstractmethod
    def find_by_user(self, user_id: str) -> List: ...
    @abstractmethod
    def find_unread_by_user(self, user_id: str) -> List: ...


class IEventSortStrategy(ABC):
    @abstractmethod
    def sort(self, events: List) -> List: ...
    @abstractmethod
    def get_name(self) -> str: ...
